"""empty message

Revision ID: 703fa7cf7e45
Revises: 6825b3100baa
Create Date: 2019-10-11 10:41:39.957029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703fa7cf7e45'
down_revision = '6825b3100baa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fullname', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'fullname')
    # ### end Alembic commands ###
